spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: krishna123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

claude:
  api:
    key: dummy
    url: https://api.anthropic.com/v1/messages
    model: claude-sonnet-4-6
    max-tokens: 10000

server:
  port: 8080
  max-http-request-header-size: 64KB
