import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from "recharts";
import { TrendingUp, Coins, Zap, Clock, LayoutDashboard } from "lucide-react";
import { getUsage } from "@/lib/api";

const fetchUsage = async () => {
  const response = await getUsage();
  return response.data;
};

export default function Usage() {
  const { data, isLoading } = useQuery({
    queryKey: ["tokenUsage"],
    queryFn: fetchUsage,
  });

  if (isLoading) {
    return (
      <div className="flex h-96 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
      </div>
    );
  }

  const chartData = [
    { name: "Input", value: data?.totalInputTokens ?? 0, color: "#3b82f6" },
    { name: "Output", value: data?.totalOutputTokens ?? 0, color: "#10b981" },
    { name: "Cache Read", value: data?.totalCacheReadTokens ?? 0, color: "#8b5cf6" },
    { name: "Cache Create", value: data?.totalCacheCreationTokens ?? 0, color: "#f59e0b" },
  ];

  const stats = [
    {
      title: "Total Cost",
      value: `$${(data?.totalCostUsd ?? 0).toFixed(4)}`,
      icon: Coins,
      description: "Total AI spend across all runs",
      color: "text-amber-500",
      bgColor: "bg-amber-500/10",
    },
    {
      title: "Total Calls",
      value: data?.totalCalls ?? 0,
      icon: Zap,
      description: "Total AI API calls made",
      color: "text-blue-500",
      bgColor: "bg-blue-500/10",
    },
    {
      title: "Input Tokens",
      value: (data?.totalInputTokens ?? 0).toLocaleString(),
      icon: Clock,
      description: "Tokens sent to the model",
      color: "text-emerald-500",
      bgColor: "bg-emerald-500/10",
    },
    {
      title: "Output Tokens",
      value: (data?.totalOutputTokens ?? 0).toLocaleString(),
      icon: TrendingUp,
      description: "Tokens generated by the model",
      color: "text-purple-500",
      bgColor: "bg-purple-500/10",
    },
  ];

  return (
    <div className="space-y-6">
      <div className="space-y-1">
        <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight">
          <LayoutDashboard className="h-6 w-6 text-primary" /> Token Usage & Cost tracking
        </h1>
        <p className="text-sm text-muted-foreground">Monitor your AI resource consumption and expenditures.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat) => (
          <Card key={stat.title} className="shadow-sm border-none bg-card/50 backdrop-blur-sm">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                {stat.title}
              </CardTitle>
              <div className={`rounded-lg p-2 ${stat.bgColor}`}>
                <stat.icon className={`h-4 w-4 ${stat.color}`} />
              </div>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stat.value}</div>
              <p className="text-xs text-muted-foreground mt-1">{stat.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <Card className="lg:col-span-2 shadow-sm border-none bg-card/50 backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="text-lg">Token Distribution</CardTitle>
          </CardHeader>
          <CardContent className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(255,255,255,0.1)" />
                <XAxis 
                  dataKey="name" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }}
                />
                <YAxis 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }}
                />
                <Tooltip 
                  contentStyle={{ 
                    backgroundColor: "hsl(var(--card))", 
                    borderColor: "hsl(var(--border))",
                    borderRadius: "8px",
                    boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)"
                  }}
                  cursor={{ fill: "rgba(255,255,255,0.05)" }}
                />
                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                  {chartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="shadow-sm border-none bg-card/50 backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="text-lg">Optimization Tips</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex gap-3 items-start">
              <div className="h-6 w-6 rounded-full bg-success/10 flex items-center justify-center shrink-0">
                <div className="h-2 w-2 rounded-full bg-success" />
              </div>
              <div className="space-y-1">
                <p className="text-sm font-medium">Prompt Caching</p>
                <p className="text-xs text-muted-foreground">Prompt caching is currently active, saving up to 90% on repeated calls.</p>
              </div>
            </div>
            <div className="flex gap-3 items-start">
              <div className="h-6 w-6 rounded-full bg-blue-500/10 flex items-center justify-center shrink-0">
                <div className="h-2 w-2 rounded-full bg-blue-500" />
              </div>
              <div className="space-y-1">
                <p className="text-sm font-medium">Model Selection</p>
                <p className="text-xs text-muted-foreground">Using Claude 3.5 Sonnet for optimal balance between intelligence and cost.</p>
              </div>
            </div>
            <div className="flex gap-3 items-start">
              <div className="h-6 w-6 rounded-full bg-amber-500/10 flex items-center justify-center shrink-0">
                <div className="h-2 w-2 rounded-full bg-amber-500" />
              </div>
              <div className="space-y-1">
                <p className="text-sm font-medium">System Prompts</p>
                <p className="text-xs text-muted-foreground">Keep system prompts concise to reduce base token usage per call.</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
